---
- hosts: all
  remote_user: sis
  tasks:
  - name: upload ssh key                
    authorized_key:
      user: sis
      state: present
      manage_dir: yes
      key: https://github.com/englert.keys
